## Data Analyst

- job: get the data that data scientists ask for -> cleans data
- mostly do  Visualisation (using Power BI) - only with current data (no predictions)

- SQL -> queries data
- POWER BI - transforms data into charts (dashboard) -> visually looks good
- Insights - Charts
- One shot Query

## Data Scientist

- data scientists also have to clean data 
  - analysts clean it to level 1, scientists clean it further.
- uses insights to make predications.

- creates predictive models using ML (machine learning).
- main job: make predictions using insights from data analyst 

- Excel (limited in terms of handling data - 100 000 rows)
- Uses Pyton - numpy, pandas - handles more data 
- Scale - Millions (processes millions of rows)
- Scikit (packages used) - Data prediction
- Matplotlib, seaborn - Develop Charts - (Rapid prototyping)
- Line by line (Step) verification - unlike analysts (long sql statements)

## numpy

- Good at working with arrays (1D data)
  - can work with 2D data, but 1D is easier 
  - Goal: work with table data
- Performant (compared to Python List)
- built on C language (that's why performant)
- Statistical oriented
  - mean, median, mode 
  - pandas makes use of all these benefits

pandas

good at working with 2D
pandas library is built into numpy 
do predictions with pandas

1. numpy
2. pandas
3. predictions

In [2]:
import numpy as np # rename numpy as np


In [2]:
marks1 = [90, 80, 20, 40]

print(marks1 * 2) # repeat operator

[90, 80, 20, 40, 90, 80, 20, 40]


In [4]:
marks1 = [90, 80, 20, 40]

marks_dbl = [mark * 2 for mark in marks1]

print(marks_dbl)

[180, 160, 40, 80]


In [ ]:
# Catering - Data Scientist
# doesn't understand python, but just wants to play wih data

# no loops needed with numpy

# array: LIST -> array

In [ ]:
# Identify matrix

np.ones(10)  # array of 10 1's

np.ones(100)  # array of 100 1's

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Array of 20 5's

np.ones(20) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [ ]:
# same like range in python - but use 'arange'
# arange - creating an array from a range

np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Task: 1 -> 10

np.arange(10) + 1

np.arange(1, 11) # same as above


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Task: Odd number
# Clue: skip value -> range takes 3 values (start, end, skip)

np.arange(1, 11, 2)


array([1, 3, 5, 7, 9])

## Operations
- Multiply, Division, Addition, Subtraction (Operation is applied to each element in array)
- Boolean (matrix / mask) -> used for filtering

In [ ]:
np.arange(1, 11) * 2 # multiple all element in array (1 -> 10) by 2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
np.arange(1, 11) / 2 # divide each element in arrange by 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
np.arange(1, 11) + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1, 11) + np.arange(1, 11) # Matrix Addition

# output 1 + 1, 2 + 2, 3 + 3 -> all the way to 10

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.array([9, 2, 3]) + np.array([1, 2, 5]) # matrix multiplication - 9 + 2, 2 + 2, 3 + 5

array([10,  4,  8])

In [ ]:
# shape is different -> size of matrix has to be the same, else error
# array1(3 nums) - array2(4 nums) -> error

In [18]:
[9, 2, 3] + [1, 2, 5] # concatenation (joins two lists)

[9, 2, 3, 1, 2, 5]

### Boolean (matrix / mask)

In [19]:
np.arange(1, 11) > 5 # it will return a boolean array (true or false - checks if each value is greater than 5)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
first_ten_nums = np.arange(1, 11) # storing our array into a variable
only_five_bm = first_ten_nums > 5
first_ten_nums[only_five_bm] # filters array - we only want numbers greater than 5, feeds array into only_five_bm

array([ 6,  7,  8,  9, 10])

In [ ]:
first_ten_nums = np.arange(1, 11)  # storing our array into a variable
first_ten_nums[first_ten_nums > 5] # if it is false - won't get in final result - we just want > 5 nums to display
# first_ten_nums -> nums 1 to 10
# [first_ten_nums > 5] -> filter condition


In [ ]:
# Task 1.1
# 1-200 only even numbers | With skip of arange

even_nums = np.arange(2, 201, 2) # start at 2 and it will show every second number

even_nums

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [28]:
# Task 1.2
# 1-200 only even numbers | Dont use skip of arange

nums = np.arange(1, 201)

nums[nums % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

### Ways to create array

1. np.array()
2. np.ones
3. np.arange

In [30]:
ages = np.random.randint(18, 60, 5) # random numbers (int) # 18, 60 -> range # 5 -> number of values

ages

array([55, 41, 46, 23, 23], dtype=int32)

In [31]:
ages = np.random.randint(
    18, 60, 5
)

ages_list = ages.tolist() # converting array into list
# before modifying - create a copy (ages_list)

print(ages_list)

[29, 41, 35, 46, 49]


In [32]:
ages = np.random.randint(18, 60, 50)  # Random data generator

print(ages)
ages[ages > 25]

[51 47 30 55 35 46 25 21 57 35 43 54 51 51 19 35 21 27 55 55 52 48 44 37
 22 33 38 37 26 32 32 37 28 43 38 27 20 33 51 31 22 37 49 53 52 51 49 28
 32 19]


array([51, 47, 30, 55, 35, 46, 57, 35, 43, 54, 51, 51, 35, 27, 55, 55, 52,
       48, 44, 37, 33, 38, 37, 26, 32, 32, 37, 28, 43, 38, 27, 33, 51, 31,
       37, 49, 53, 52, 51, 49, 28, 32], dtype=int32)

In [33]:
ages_list

[29, 41, 35, 46, 49]

In [ ]:
%%time
# shows you how long it took to run/process
ages_list

CPU times: total: 0 ns
Wall time: 9.3 μs


[29, 41, 35, 46, 49]